### ISSUE TITLE
how to save expanded state

### ISSUE THREAD

**Issue by l2dev** [italankin/android-expandable-list#1]
Im using fragments. If I expand some recyclerview Items and go to another fragment, when I come back to previous fragment I want it to restore expanded state.

**Comment by italankin** [comment]
Depending on how you create and save your dataset, you can use `onSaveInstanceState` and restore expanded state in `onCreate` or `onViewCreated`. `setRetainInstance(true)` is also a solution.

**Comment by l2dev** [comment]
And are you sure it wont cause memory leaks?

**Comment by italankin** [comment]
It's hard to talk about this without a concrete example.

When you use `setRetainInstance(true)` it's easy to introduce memory leaks (e.g. leak views).

`ExpandableList` is just a data structure, such as `ArrayList` or `HashMap`.
You should follow general rules (there are many articles and tutorials on this) to avoid memory leaks.
